apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
data:
  MYSQL_HOST: "localhost"
  MYSQL_USER: "user"
  MYSQL_PASSWORD: "password"
  MYSQL_DATABASE: "lms"
  MYSQL_ROOT_PASSWORD: "rootpassword"


